#!/usr/bin/env python3
"""Deterministic seed-data generator for the HireWise skill taxonomy.

Outputs `skills-seed.json` containing 320 canonical skills across domains,
each with a list of aliases. "JS", "Javascript", "JavaScript" resolve to the
same canonical skill. Aliases are normalised to lowercase for case-insensitive
query-time resolution.
"""
import json

TAXONOMY = {
    "Programming Languages": [
        ("JavaScript", ["js", "javascript", "ecmascript", "es6", "es2015", "js/jsx"]),
        ("TypeScript", ["ts", "typescript", "tsx", "typescriptjs"]),
        ("Python", ["python", "python3", "py", "python 3"]),
        ("Java", ["java", "java 8", "java 11", "java11"]),
        ("C++", ["c++", "cpp", "c plus plus", "cplusplus"]),
        ("C", ["c", "c programming", "ansi c", "posix c"]),
        ("C#", ["c#", "csharp", "c sharp", "c-sharp", "dotnet c#"]),
        ("Go", ["go", "golang", "go language"]),
        ("Rust", ["rust", "rustlang", "rust language"]),
        ("Ruby", ["ruby", "ruby language", "ruby on rails lang"]),
        ("PHP", ["php", "php7", "php8", "php 8"]),
        ("Swift", ["swift", "swift language", "swift ios"]),
        ("Kotlin", ["kotlin", "kotlin lang", "kotlin android"]),
        ("Scala", ["scala", "scala lang"]),
        ("R", ["r", "r language", "rstats"]),
        ("Dart", ["dart", "dart lang"]),
        ("Perl", ["perl", "perl5"]),
        ("Lua", ["lua", "lua lang"]),
        ("Haskell", ["haskell", "hs", "haskell language"]),
        ("Elixir", ["elixir", "elixir lang"]),
        ("Zig", ["zig", "zig lang"]),
        ("VBA", ["vba", "visual basic for applications"]),
        ("Bash", ["bash", "bash scripting", "shell scripting", "sh"]),
        ("PowerShell", ["powershell", "ps1"]),
        ("SQL", ["sql", "structured query language", "sql programming"]),
        ("MATLAB", ["matlab", "matlab programming"]),
        ("Julia", ["julia", "julia lang"]),
        ("Groovy", ["groovy", "groovy lang"]),
        ("F#", ["f#", "fsharp", "f sharp"]),
        ("Objective-C", ["objective-c", "objectivec", "obj-c"]),
        ("Assembly", ["assembly", "asm", "assembly language"]),
        ("Delphi", ["delphi", "pascal", "object pascal"]),
    ],
    "Web Development": [
        ("React", ["react", "reactjs", "react.js", "react js"]),
        ("Vue.js", ["vue", "vue.js", "vuejs", "vue 3"]),
        ("Angular", ["angular", "angularjs", "angular 2+", "ng"]),
        ("Next.js", ["next", "next.js", "nextjs", "next.js framework"]),
        ("Node.js", ["node", "node.js", "nodejs", "node js"]),
        ("Express", ["express", "express.js", "expressjs", "express.js framework"]),
        ("NestJS", ["nestjs", "nest", "nest.js"]),
        ("Svelte", ["svelte", "sveltejs", "svelte.js"]),
        ("Remix", ["remix", "remix.js", "remix.run"]),
        ("Gatsby", ["gatsby", "gatsby.js", "gatsbyjs"]),
        ("Astro", ["astro", "astro.js"]),
        ("Redux", ["redux", "reduxjs", "redux toolkit", "rtk"]),
        ("Webpack", ["webpack", "webpackjs"]),
        ("Vite", ["vite", "vitejs"]),
        ("Tailwind CSS", ["tailwind", "tailwindcss", "tailwind css", "tailwind.js"]),
        ("HTML", ["html", "html5", "html 5"]),
        ("CSS", ["css", "css3", "css 3", "stylesheets"]),
        ("SASS", ["sass", "scss", "sass/scss"]),
        ("jQuery", ["jquery", "jquery.js", "jq"]),
        ("Jest", ["jest", "jestjs", "jest testing"]),
        ("Cypress", ["cypress", "cypress.io", "cypress testing"]),
        ("Storybook", ["storybook", "storybook.js"]),
        ("Three.js", ["three", "three.js", "threejs", "three.js library"]),
        ("D3.js", ["d3", "d3.js", "d3js"]),
        ("Socket.IO", ["socket.io", "socketio", "socket.io library"]),
        ("Fastify", ["fastify", "fastify.js"]),
    ],
    "Backend & Databases": [
        ("PostgreSQL", ["postgres", "postgresql", "pgsql", "postgresql database"]),
        ("MySQL", ["mysql", "mysql database", "mysql db"]),
        ("MongoDB", ["mongo", "mongodb", "mongo db"]),
        ("Redis", ["redis", "redis cache", "redis db"]),
        ("SQLite", ["sqlite", "sqlite3", "sqlite database"]),
        ("Oracle Database", ["oracle", "oracle db", "oracle database", "oracle sql"]),
        ("Microsoft SQL Server", ["mssql", "sql server", "microsoft sql server", "t-sql"]),
        ("Elasticsearch", ["elasticsearch", "elastic search", "es database"]),
        ("Apache Kafka", ["kafka", "apache kafka", "kafka messaging"]),
        ("GraphQL", ["graphql", "graphql api"]),
        ("REST API", ["rest", "rest api", "restful api", "restful", "restful services"]),
        ("gRPC", ["grpc", "grpc api", "grpc framework"]),
        ("Django", ["django", "django framework", "django python"]),
        ("Flask", ["flask", "flask framework"]),
        ("FastAPI", ["fastapi", "fast api"]),
        ("Spring Boot", ["spring boot", "springboot", "spring boot framework"]),
        ("Hibernate", ["hibernate", "hibernate orm"]),
        ("Prisma", ["prisma", "prisma orm"]),
        ("Sequelize", ["sequelize", "sequelize orm"]),
        ("Entity Framework", ["entity framework", "ef core", "entity framework core"]),
        ("Laravel", ["laravel", "laravel framework", "laravel php"]),
        ("RabbitMQ", ["rabbitmq", "rabbit mq", "rabbit mq messaging"]),
        ("Apollo GraphQL", ["apollo", "apollo graphql", "apollo server"]),
        ("Docker", ["docker", "docker containers", "docker containerization"]),
        ("Kubernetes", ["k8s", "kubernetes", "kubernetes orchestration", "k8s orchestration"]),
        ("Nginx", ["nginx", "nginx server", "nginx web server"]),
        ("Apache HTTP Server", ["apache", "apache httpd", "apache web server"]),
        ("Terraform", ["terraform", "terraform iac", "hashicorp terraform"]),
        ("Ansible", ["ansible", "ansible automation"]),
        ("Jenkins", ["jenkins", "jenkins ci"]),
        ("GitHub Actions", ["github actions", "gh actions"]),
        ("GitLab CI", ["gitlab ci", "gitlab ci/cd", "gitlab pipelines"]),
    ],
    "Cloud & DevOps": [
        ("Amazon Web Services", ["aws", "amazon web services", "aws cloud"]),
        ("Microsoft Azure", ["azure", "microsoft azure", "ms azure"]),
        ("Google Cloud Platform", ["gcp", "google cloud", "google cloud platform", "google cloud platform (gcp)"]),
        ("Amazon S3", ["s3", "amazon s3", "aws s3"]),
        ("AWS Lambda", ["lambda", "aws lambda", "lambda functions"]),
        ("Docker Compose", ["docker compose", "docker-compose"]),
        ("Helm", ["helm", "helm charts", "kubernetes helm"]),
        ("ArgoCD", ["argocd", "argo cd", "argo cd gitops"]),
        ("Prometheus", ["prometheus", "prometheus monitoring"]),
        ("Grafana", ["grafana", "grafana dashboards"]),
        ("Datadog", ["datadog", "datadog monitoring"]),
        ("GitHub", ["github", "git github", "github vcs"]),
        ("Git", ["git", "git version control", "git vcs"]),
        ("CI/CD", ["ci/cd", "cicd", "continuous integration", "continuous deployment"]),
        ("Linux", ["linux", "linux os", "linux administration"]),
        ("Ubuntu", ["ubuntu", "ubuntu linux"]),
        ("macOS", ["macos", "mac os", "mac os x"]),
        ("Windows Server", ["windows server", "windows server administration"]),
    ],
    "Mobile Development": [
        ("React Native", ["react native", "react-native", "rn mobile"]),
        ("Flutter", ["flutter", "flutter framework"]),
        ("iOS Development", ["ios", "ios development", "iphone development"]),
        ("Android Development", ["android", "android development", "android apps"]),
        ("Expo", ["expo", "expo sdk", "expo react native"]),
        ("SwiftUI", ["swiftui", "swift ui"]),
        ("Android SDK", ["android sdk", "android sdk development"]),
    ],
    "Data Science & ML": [
        ("Machine Learning", ["ml", "machine learning", "machine-learning", "machine learning engineering"]),
        ("Deep Learning", ["deep learning", "deep learning models", "dl"]),
        ("Natural Language Processing", ["nlp", "natural language processing", "nlp engineering"]),
        ("Computer Vision", ["cv", "computer vision"]),
        ("TensorFlow", ["tensorflow", "tf", "tensorflow framework"]),
        ("PyTorch", ["pytorch", "pytorch framework", "torch"]),
        ("scikit-learn", ["scikit-learn", "sklearn", "scikit learn"]),
        ("Pandas", ["pandas", "pandas python", "pandas dataframes"]),
        ("NumPy", ["numpy", "numpy python", "numpy arrays"]),
        ("Matplotlib", ["matplotlib", "matplotlib plotting"]),
        ("Jupyter", ["jupyter", "jupyter notebook", "jupyter notebooks"]),
        ("Apache Spark", ["spark", "apache spark", "spark big data"]),
        ("Hadoop", ["hadoop", "apache hadoop"]),
        ("Tableau", ["tableau", "tableau analytics"]),
        ("Power BI", ["power bi", "powerbi", "microsoft power bi"]),
        ("Data Engineering", ["data engineering", "data pipeline engineering"]),
        ("BigQuery", ["bigquery", "google bigquery", "gbq"]),
        ("Apache Airflow", ["airflow", "apache airflow", "airflow orchestration"]),
        ("dbt", ["dbt", "data build tool", "dbt analytics"]),
        ("Snowflake", ["snowflake", "snowflake cloud warehouse"]),
        ("Apache Flink", ["flink", "apache flink"]),
        ("Databricks", ["databricks", "databricks platform"]),
        ("LLM Fine-Tuning", ["llm fine-tuning", "llm fine tuning", "large language model fine-tuning", "llm tuning"]),
        ("RAG", ["rag", "retrieval augmented generation", "rag systems"]),
        ("LangChain", ["langchain", "langchain framework"]),
    ],
    "AI & Emerging Tech": [
        ("Artificial Intelligence", ["ai", "artificial intelligence"]),
        ("OpenAI API", ["openai", "openai api", "gpt api"]),
        ("Hugging Face", ["hugging face", "huggingface", "huggingface transformers"]),
        ("MLOps", ["mlops", "ml ops", "machine learning ops"]),
        ("Blockchain", ["blockchain", "blockchain technology"]),
        ("Solidity", ["solidity", "solidity smart contracts"]),
        ("Smart Contracts", ["smart contracts", "ethereum smart contracts"]),
        ("Web3", ["web3", "web 3", "web3 development"]),
        ("Ethereum", ["ethereum", "eth", "ethereum blockchain"]),
        ("IoT", ["iot", "internet of things", "internet of things development"]),
        ("AR/VR", ["ar/vr", "arvr", "augmented reality", "virtual reality", "ar", "vr"]),
        ("Unity", ["unity", "unity engine", "unity3d"]),
        ("Unreal Engine", ["unreal", "unreal engine", "ue5"]),
    ],
    "Design & UX": [
        ("Figma", ["figma", "figma design"]),
        ("Adobe XD", ["adobe xd", "xd"]),
        ("Adobe Photoshop", ["photoshop", "adobe photoshop", "ps"]),
        ("Adobe Illustrator", ["illustrator", "adobe illustrator", "ai design"]),
        ("UI/UX Design", ["ui/ux", "ui ux", "uiux", "ux/ui", "user interface design"]),
        ("UX Research", ["ux research", "user research"]),
        ("Prototyping", ["prototyping", "rapid prototyping", "product prototyping"]),
        ("Design Systems", ["design systems", "component libraries"]),
        ("Sketch", ["sketch", "sketch app"]),
        ("InVision", ["invision", "invision app"]),
    ],
    "Product, Project & Business": [
        ("Agile", ["agile", "agile methodology", "agile frameworks"]),
        ("Scrum", ["scrum", "scrum framework", "scrum master"]),
        ("Kanban", ["kanban", "kanban boards"]),
        ("Product Management", ["product management", "pm", "product manager"]),
        ("Project Management", ["project management", "project manager"]),
        ("Jira", ["jira", "jira software", "atlassian jira"]),
        ("Confluence", ["confluence", "atlassian confluence"]),
        ("Notion", ["notion", "notion workspace"]),
        ("Slack", ["slack", "slack messaging"]),
        ("Microsoft Teams", ["ms teams", "microsoft teams", "teams"]),
        ("Google Workspace", ["google workspace", "g suite", "gsuite"]),
        ("Salesforce", ["salesforce", "salesforce crm", "sf crm"]),
        ("HubSpot", ["hubspot", "hubspot crm"]),
        ("SEO", ["seo", "search engine optimization"]),
        ("Google Analytics", ["google analytics", "ga4", "analytics"]),
        ("Content Strategy", ["content strategy", "content planning"]),
        ("Copywriting", ["copywriting", "content writing"]),
        ("Digital Marketing", ["digital marketing", "online marketing"]),
        ("Data Analysis", ["data analysis", "data analytics", "analytical skills"]),
        ("Microsoft Excel", ["excel", "microsoft excel", "spreadsheets", "ms excel"]),
        ("Technical Writing", ["technical writing", "documentation", "tech writing"]),
        ("Public Speaking", ["public speaking", "presentations"]),
        ("Leadership", ["leadership", "team leadership"]),
        ("Communication", ["communication", "interpersonal communication", "verbal communication"]),
    ],
    "Cybersecurity": [
        ("Cybersecurity", ["cybersecurity", "cyber security", "information security"]),
        ("Penetration Testing", ["pentesting", "penetration testing", "pen testing"]),
        ("SIEM", ["siem", "security information and event management"]),
        ("IAM", ["iam", "identity and access management"]),
        ("Application Security", ["appsec", "application security", "app security"]),
        ("Network Security", ["network security", "netsec"]),
        ("OWASP", ["owasp", "owasp top 10"]),
        ("SOC", ["soc", "security operations center"]),
        ("Compliance (SOC 2, ISO 27001)", ["compliance", "soc 2", "iso 27001", "soc2"]),
    ],
    "Finance & Other": [
        ("Financial Modeling", ["financial modeling", "financial models", "fin modeling"]),
        ("Accounting", ["accounting", "bookkeeping"]),
        ("QuickBooks", ["quickbooks", "quickbooks accounting"]),
        ("SAP", ["sap", "sap erp", "sap systems"]),
        ("ERP Systems", ["erp", "erp systems", "enterprise resource planning"]),
        ("Supply Chain Management", ["scm", "supply chain management", "supply chain"]),
        ("Human Resources", ["hr", "human resources", "hr management"]),
        ("Recruitment", ["recruitment", "talent acquisition", "hiring"]),
        ("Customer Support", ["customer support", "customer service", "client support"]),
        ("Sales", ["sales", "sales management", "business development"]),
    ],
}

TAXONOMY.update({
    "Frontend & CSS Ecosystem": [
        ("Styled Components", ["styled-components", "styled components"]),
        ("CSS Modules", ["css modules"]),
        ("Emotion", ["emotion", "emotion css", "@emotion"]),
        ("Bootstrap", ["bootstrap", "bootstrap 5", "bootstrap css"]),
        ("Material UI", ["mui", "material ui", "material-ui", "material design"]),
        ("Ant Design", ["antd", "ant design", "ant-design"]),
        ("Chakra UI", ["chakra", "chakra ui", "chakra-ui"]),
        ("Headless UI", ["headless ui"]),
        ("React Query", ["react query", "tanstack query", "tanstack react-query"]),
        ("Zustand", ["zustand", "zustand state"]),
        ("MobX", ["mobx", "mobx state"]),
        ("XState", ["xstate", "xstate state machine", "state machines"]),
        ("Storybook Docs", ["storybook docs"]),
        ("Preact", ["preact", "preact framework"]),
        ("SolidJS", ["solid", "solidjs", "solid.js"]),
        ("Lit", ["lit", "lit element", "lit web components"]),
        ("Web Components", ["web components", "custom elements"]),
        ("Accessibility (a11y)", ["a11y", "accessibility", "web accessibility", "wcag"]),
        ("Responsive Design", ["responsive design", "responsive web design"]),
        ("Progressive Web Apps", ["pwa", "progressive web apps", "progressive web app"]),
        ("WebAssembly", ["wasm", "webassembly", "web assembly"]),
        ("Vitest", ["vitest", "vitest testing"]),
        ("Playwright", ["playwright", "playwright testing", "playwright e2e"]),
        ("React Testing Library", ["rtl", "react testing library"]),
        ("ESLint", ["eslint", "eslint linting"]),
        ("Prettier", ["prettier", "prettier formatting"]),
        ("Babel", ["babel", "babeljs", "babel transpiler"]),
        ("esbuild", ["esbuild", "esbuild bundler"]),
        ("Rollup", ["rollup", "rollup bundler"]),
        ("Turborepo", ["turborepo", "turbo"]),
        ("Nx", ["nx", "nx monorepo"]),
        ("Lerna", ["lerna", "lerna monorepo"]),
        ("Yarn", ["yarn", "yarn package manager"]),
        ("pnpm", ["pnpm", "pnpm package manager"]),
        ("NPM", ["npm", "npm packages"]),
        ("Micro-frontends", ["micro-frontends", "micro frontend"]),
    ],
    "Backend & Infrastructure": [
        ("NestJS Modules", ["nest modules"]),
        ("Koa", ["koa", "koa.js", "koajs"]),
        ("Hono", ["hono", "hono.js"]),
        ("Socket.IO Server", ["socketio server"]),
        ("BullMQ", ["bull", "bullmq", "bull queue"]),
        ("Celery", ["celery", "celery tasks"]),
        ("Sidekiq", ["sidekiq", "sidekiq jobs"]),
        ("RabbitMQ Exchanges", ["rabbitmq exchanges"]),
        ("Kubernetes Operators", ["kubernetes operators"]),
        ("Istio", ["istio", "istio service mesh"]),
        ("Envoy", ["envoy", "envoy proxy"]),
        ("Consul", ["consul", "hashicorp consul"]),
        ("Vault", ["vault", "hashicorp vault", "secrets management"]),
        ("Packer", ["packer", "hashicorp packer"]),
        ("CloudFormation", ["cloudformation", "aws cloudformation"]),
        ("AWS CDK", ["cdk", "aws cdk", "cloud development kit"]),
        ("Pulumi", ["pulumi", "pulumi iac"]),
        ("Spinnaker", ["spinnaker", "spinnaker deployments"]),
        ("Tekton", ["tekton", "tekton pipelines"]),
        ("Octopus Deploy", ["octopus deploy"]),
        ("Load Balancing", ["load balancing", "load balancers"]),
        ("CDN", ["cdn", "content delivery network"]),
        ("Cloudflare", ["cloudflare", "cloudflare cdn"]),
        ("Vercel", ["vercel", "vercel hosting"]),
        ("Netlify", ["netlify", "netlify hosting"]),
        ("Heroku", ["heroku", "heroku hosting"]),
        ("DigitalOcean", ["digitalocean", "digital ocean"]),
        ("Linode", ["linode", "linode cloud"]),
        ("Firebase", ["firebase", "firebase platform"]),
        ("Supabase", ["supabase", "supabase backend"]),
        ("CockroachDB", ["cockroachdb", "cockroach db"]),
        ("Cassandra", ["cassandra", "apache cassandra"]),
        ("CouchDB", ["couchdb", "apache couchdb"]),
        ("Neo4j", ["neo4j", "neo4j graph"]),
        ("DynamoDB", ["dynamodb", "aws dynamodb"]),
        ("InfluxDB", ["influxdb", "influxdb timeseries"]),
        ("TimescaleDB", ["timescaledb", "timescaledb timeseries"]),
        ("ClickHouse", ["clickhouse", "clickhouse analytics"]),
        ("Memcached", ["memcached", "memcached caching"]),
        ("MariaDB", ["mariadb", "mariadb database"]),
        ("Firebase Firestore", ["firestore", "cloud firestore"]),
        ("Hasura", ["hasura", "hasura graphql"]),
        ("tRPC", ["trpc", "trpc framework"]),
        ("Drizzle ORM", ["drizzle", "drizzle orm", "drizzlekit"]),
        ("Kysely", ["kysely", "kysely query builder"]),
        ("Knex.js", ["knex", "knex.js", "knexjs"]),
        ("TypeORM", ["typeorm", "type orm"]),
        ("MyBatis", ["mybatis", "mybatis framework"]),
    ],
    "Data & Analytics": [
        ("Apache NiFi", ["nifi", "apache nifi"]),
        ("dbt Core", ["dbt core"]),
        ("Looker", ["looker", "google looker"]),
        ("Metabase", ["metabase", "metabase analytics"]),
        ("Redash", ["redash", "redash dashboards"]),
        ("A/B Testing", ["a/b testing", "ab testing", "experimentation"]),
        ("Statistics", ["statistics", "statistical analysis"]),
        ("Hypothesis Testing", ["hypothesis testing", "statistical hypothesis testing"]),
        ("Time Series Analysis", ["time series", "time series analysis"]),
        ("Feature Engineering", ["feature engineering"]),
        ("Data Visualization", ["data visualization", "data viz"]),
        ("ETL", ["etl", "etl pipelines", "extract transform load"]),
        ("Data Warehousing", ["data warehousing", "data warehouse"]),
        ("Stream Processing", ["stream processing", "real-time streaming"]),
        ("Data Governance", ["data governance"]),
        ("Data Quality", ["data quality", "data quality engineering"]),
        ("Experimentation Platforms", ["experimentation platforms"]),
        ("Causal Inference", ["causal inference", "causal analysis"]),
        ("Survival Analysis", ["survival analysis"]),
        ("Bayesian Methods", ["bayesian", "bayesian methods", "bayesian statistics"]),
        ("Reinforcement Learning", ["rl", "reinforcement learning"]),
        ("Generative AI", ["genai", "generative ai", "generative ai applications"]),
        ("Prompt Engineering", ["prompt engineering", "prompt design"]),
        ("Embeddings", ["embeddings", "vector embeddings"]),
        ("Vector Databases", ["vector databases", "vector db", "vectordb", "vector search"]),
        ("Pinecone", ["pinecone", "pinecone vector db"]),
        ("Weaviate", ["weaviate", "weaviate vector db"]),
        ("Milvus", ["milvus", "milvus vector db"]),
        ("FAISS", ["faiss", "facebook faiss"]),
        ("Transformers (Architecture)", ["transformers", "transformer architecture"]),
        ("Diffusion Models", ["diffusion models", "diffusion"]),
        ("Stable Diffusion", ["stable diffusion", "stablediffusion"]),
        ("OpenCV", ["opencv", "opencv computer vision"]),
        ("YOLO", ["yolo", "yolo object detection"]),
        ("Image Segmentation", ["image segmentation", "segmentation models"]),
        ("Speech Recognition", ["asr", "speech recognition", "automatic speech recognition"]),
        ("Text-to-Speech", ["tts", "text to speech", "text-to-speech"]),
        ("Machine Translation", ["machine translation", "nmt"]),
        ("Named Entity Recognition", ["ner", "named entity recognition"]),
        ("Text Classification", ["text classification", "document classification"]),
    ],
    "Mobile & Desktop": [
        ("Swift Package Manager", ["spm", "swift package manager"]),
        ("CocoaPods", ["cocoapods", "cocoa pods"]),
        ("Gradle", ["gradle", "gradle android"]),
        ("Maven", ["maven", "apache maven"]),
        ("Jetpack Compose", ["jetpack compose", "compose"]),
        ("Coroutines", ["coroutines", "kotlin coroutines"]),
        ("RxJava", ["rxjava", "rx java", "reactive java"]),
        ("RxJS", ["rxjs", "reactive extensions", "reactivex"]),
        ("React Navigation", ["react navigation"]),
        ("App Store Optimization", ["aso", "app store optimization"]),
        ("Apple TestFlight", ["testflight"]),
        ("Google Play Console", ["google play console", "play console"]),
        ("Capacitor", ["capacitor", "capacitorjs", "capacitor.js"]),
        ("Cordova", ["cordova", "apache cordova"]),
        ("Electron", ["electron", "electron desktop", "electron.js"]),
        ("Tauri", ["tauri", "tauri desktop"]),
        ("Qt", ["qt", "qt framework"]),
        ("WinUI", ["winui", "winui 3"]),
        ("WPF", ["wpf", "windows presentation foundation"]),
    ],
    "Quality, Security & Reliability": [
        ("Test-Driven Development", ["tdd", "test driven development"]),
        ("Unit Testing", ["unit testing", "unit tests"]),
        ("Integration Testing", ["integration testing"]),
        ("End-to-End Testing", ["e2e testing", "end to end testing"]),
        ("Load Testing", ["load testing", "performance testing", "jmeter"]),
        ("Static Analysis", ["static analysis", "static code analysis"]),
        ("Code Review", ["code review", "peer review"]),
        ("Git Workflows", ["git workflow", "git branching", "gitflow", "git flow"]),
        ("Monorepo Management", ["monorepo"]),
        ("Observability", ["observability"]),
        ("Distributed Tracing", ["distributed tracing", "opentelemetry", "tracing"]),
        ("Logging", ["logging", "log management"]),
        ("Incident Management", ["incident management", "on-call"]),
        ("SRE", ["sre", "site reliability engineering"]),
        ("Chaos Engineering", ["chaos engineering"]),
        ("Disaster Recovery", ["disaster recovery", "dr planning"]),
        ("API Security", ["api security", "api gateway security"]),
        ("OAuth 2.0", ["oauth2", "oauth 2.0", "oauth"]),
        ("JWT", ["jwt", "json web tokens", "json web token"]),
        ("Single Sign-On", ["sso", "single sign-on", "single sign on"]),
        ("SAML", ["saml", "saml sso"]),
        ("LDAP", ["ldap", "active directory", "ad ldap"]),
        ("GDPR", ["gdpr", "gdpr compliance", "data privacy"]),
        ("Zero Trust", ["zero trust", "zero trust security"]),
        ("Threat Modeling", ["threat modeling"]),
        ("Security Audits", ["security audits", "security audit"]),
        ("Vulnerability Management", ["vulnerability management", "patch management"]),
    ],
    "Design, Product & Business": [
        ("Motion Design", ["motion design", "motion graphics"]),
        ("3D Modeling", ["3d modeling", "3d design"]),
        ("Blender", ["blender", "blender 3d"]),
        ("After Effects", ["after effects", "adobe after effects"]),
        ("Premiere Pro", ["premiere", "adobe premiere pro", "video editing"]),
        ("Information Architecture", ["ia", "information architecture"]),
        ("Interaction Design", ["interaction design", "ixd"]),
        ("Service Design", ["service design"]),
        ("Design Thinking", ["design thinking"]),
        ("User Interviews", ["user interviews"]),
        ("A/B Test Design", ["experiment design", "a/b test design"]),
        ("OKRs", ["okrs", "objectives and key results"]),
        ("KPI Definition", ["kpis", "kpi definition", "metrics"]),
        ("Roadmapping", ["roadmapping", "product roadmapping"]),
        ("Stakeholder Management", ["stakeholder management"]),
        ("Business Strategy", ["business strategy", "strategic planning"]),
        ("Market Research", ["market research"]),
        ("Competitive Analysis", ["competitive analysis", "competitor analysis"]),
        ("Go-to-Market", ["gtm", "go-to-market", "g2m"]),
        ("Growth Marketing", ["growth marketing", "growth hacking"]),
        ("Performance Marketing", ["performance marketing", "paid acquisition"]),
        ("Email Marketing", ["email marketing", "email campaigns"]),
        ("Social Media Marketing", ["social media marketing", "social media"]),
        ("Influencer Marketing", ["influencer marketing"]),
        ("Affiliate Marketing", ["affiliate marketing"]),
        ("Conversion Optimization", ["cro", "conversion rate optimization"]),
        ("Funnel Analysis", ["funnel analysis", "marketing funnels"]),
        ("Customer Success", ["customer success", "cs"]),
        ("Account Management", ["account management", "client management"]),
        ("B2B Sales", ["b2b sales", "enterprise sales"]),
        ("CRM Management", ["crm", "crm management"]),
        ("Stripe Integration", ["stripe", "stripe payments", "stripe api"]),
        ("Payment Processing", ["payments", "payment processing", "payment gateways"]),
        ("E-commerce Platforms", ["ecommerce", "e-commerce", "shopify", "shopify development"]),
        ("Inventory Management", ["inventory management"]),
        ("Logistics", ["logistics", "logistics management"]),
        ("Procurement", ["procurement", "vendor management"]),
        ("Change Management", ["change management"]),
        ("Training & Development", ["training", "l&d", "learning and development"]),
        ("Organizational Design", ["org design", "organizational design"]),
        ("Compensation & Benefits", ["comp & ben", "compensation and benefits"]),
    ],
    "Domain Expertise": [
        ("Fintech", ["fintech", "financial technology"]),
        ("Healthcare IT", ["healthcare it", "healthtech", "health it"]),
        ("EdTech", ["edtech", "education technology"]),
        ("SaaS", ["saas", "software as a service"]),
        ("Marketplaces", ["marketplaces", "marketplace platforms"]),
        ("AdTech", ["adtech", "advertising technology"]),
        ("MarTech", ["martech", "marketing technology"]),
        ("Legal Tech", ["legaltech", "legal tech"]),
        ("PropTech", ["proptech", "property technology"]),
        ("GovTech", ["govtech", "government technology"]),
        ("HIPAA Compliance", ["hipaa", "hipaa compliance"]),
        ("PCI DSS", ["pci dss", "pci compliance"]),
        ("HL7/FHIR", ["hl7", "fhir", "hl7/fhir", "healthcare interoperability"]),
        ("SCADA", ["scada", "industrial automation"]),
        ("Embedded Systems", ["embedded", "embedded systems", "embedded development"]),
        ("Firmware", ["firmware", "firmware development"]),
        ("RTOS", ["rtos", "real-time operating systems"]),
        ("FPGA", ["fpga", "fpga development"]),
        ("Robotics", ["robotics", "robotics engineering"]),
        ("Autonomous Systems", ["autonomous systems", "self-driving"]),
        ("Signal Processing", ["dsp", "signal processing", "digital signal processing"]),
        ("Simulation", ["simulation", "simulation modeling"]),
    ],
})


def main():
    skills = []
    aliases = []
    skill_id = 1
    for category, entries in TAXONOMY.items():
        for canonical, alias_list in sorted(entries, key=lambda x: x[0]):
            slug = canonical.lower().replace("(", "").replace(")", "").replace("/", "-").replace(" ", "-")
            skills.append({"id": skill_id, "name": canonical, "slug": slug, "category": category})
            for a in alias_list:
                if a.lower() != canonical.lower():
                    aliases.append({"alias": a.lower(), "skillId": skill_id})
            skill_id += 1

    assert len(skills) > 300, f"Expected 300+ skills, got {len(skills)}"
    out = {"skills": skills, "aliases": aliases}
    with open("/home/ubuntu/hirewise/scripts/skills-seed.json", "w") as f:
        json.dump(out, f, indent=1)
    print(f"Skills: {len(skills)}, Aliases: {len(aliases)}")


if __name__ == "__main__":
    main()
